resumes/urls.py
from django.urls import path
from resumes.views import home, new, show, edit, delete

app_name = "resumes"
urlpatterns = [
    path("", home, name="home"),
    path("new/", new, name="new"),
    path("<int:id>/", show, name="show"),
    path("<int:id>/edit", edit, name="edit"),
    path("<int:id>/delete", delete, name="delete"),
]

resumes/models.py
from django.db import models


# Create your models here.
class Resume(models.Model):
    title = models.CharField(max_length=50, null=True)
    skill = models.CharField(max_length=50, null=True)
    location = models.CharField(max_length=50, null=True)
    content = models.TextField(null=True)

resumes/forms.py
from django.forms import ModelForm
from .models import Resume


class ResumeForm(ModelForm):

    class Meta:
        model = Resume
        fields = ["title", "skill", "location", "content"]

resumes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Resume
from .forms import ResumeForm

# Create your views here.


def home(request):
    if request.POST:
        form = ResumeForm(request.POST)
        form.save()
        return redirect("resumes:home")
    resumes = Resume.objects.all()
    return render(request, "resumes/home.html", {"resumes": resumes})


def new(request):
    resume = Resume()
    form = ResumeForm(instance=resume)
    return render(request, "resumes/new.html", {"form": form})


def show(request, id):
    resume = get_object_or_404(Resume, id=id)
    if request.POST:
        form = ResumeForm(request.POST, instance=resume)
        form.save()
        return redirect("resumes:home")
    return render(request, "resumes/show.html", {"resume": resume})


def edit(request, id):
    resume = get_object_or_404(Resume, id=id)
    form = ResumeForm(instance=resume)
    return render(request, "resumes/edit.html", {"resume": resume, "form": form})


def delete(request, id):
    resume = get_object_or_404(Resume, id=id)
    if request.POST:
        resume.delete()
        return redirect("resumes:home")
    return render(request, "resumes/delete.html")

resumes/templates/resumes/delete.html
{% extends "shared/layout.html" %} {% block "content" %}

<h1>delete?</h1>

<form method="POST">
  {% csrf_token %}

  <button>yes</button>
</form>

{% endblock %}

resumes/templates/resumes/edit.html
{% extends "shared/layout.html" %} {% block "content" %}

<h1>edit</h1>

<form method="POST" action="{% url "resumes:show" resume.id %}">
  {% csrf_token %} {{form.as_p}}

  <button>edit</button>
</form>

{% endblock %}

resumes/templates/resumes/home.html
{% extends "shared/layout.html" %}
{% block "content" %}

<h1>Resume Title:</h1>
<a href="{% url "resumes:new" %}">new resume</a>

<ul>
    {% for resume in resumes  %}
    <li>
        <a href="{% url "resumes:show" resume.id %}">{{resume.title}}</a>
    </li>
    {% endfor %}
</ul>




{% endblock %}

resumes/templates/resumes/new.html
{% extends "shared/layout.html" %} {% block "content" %}

<h1>new resume</h1>

<form method="POST" action="{% url "resumes:home" %}">
  {% csrf_token %} {{form.as_p}}

  <button>add</button>
</form>

{% endblock %}

resumes/templates/resumes/show.html
{% extends "shared/layout.html" %} {% block "content" %}

<h1>Title:{{resume.title}}</h1>
<h1>skill:{{resume.skill}}</h1>
<p>content:{{resume.content}}</p>

<footer>
    <a href="{% url "resumes:edit" resume.id %}">edit</a>
    <a href="{% url "resumes:delete" resume.id %}">delete</a>

</footer>


{% endblock %}